version: "3"

networks:
    laravel:

services:
    nginx:
        platform: linux/x86_64
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            # - ./src:/var/www/html
            - ../bahasa-booster:/var/www/html/bahasa-booster
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../aneka_logistic:/var/www/html/aneka_logistic
            - ./nginx/aneka.conf:/etc/nginx/conf.d/aneka.conf
            - ../tmi:/var/www/html/tmi
            - ./nginx/tmi.conf:/etc/nginx/conf.d/tmi.conf
            - ../lkihi-ui:/var/www/html/lkihi-ui
            - ./nginx/lkihi.conf:/etc/nginx/conf.d/lkihi.conf
        depends_on:
            - php
        networks:
            - laravel

    php:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: azzam
                uid: 1000
        container_name: php
        volumes:
            # - ./src:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ../bahasa-booster:/var/www/html/bahasa-booster
            - ../aneka_logistic:/var/www/html/aneka_logistic
            - ../tmi:/var/www/html/tmi
            - ../lkihi-ui:/var/www/html/lkihi-ui
        ports:
            - "9000:9000"
        networks:
            - laravel
