version: "3"

networks:
    laravel:

services:
    nginx:
        platform: linux/x86_64
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            # - ./src:/var/www/html
            # - ../try-laravel:/var/www/html
            - ../try-laravel:/var/www/html/try-laraval
            - ../shayna-backend-laravue:/var/www/html/shayna-backend-laravue
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/laravue.conf:/etc/nginx/conf.d/laravue.conf
        depends_on:
            - php
        networks:
            - laravel

    php:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: azzam
                uid: 1000
        container_name: php
        volumes:
            # - ./src:/var/www/html
            # - ../try-laravel:/var/www/html
            - ../try-laravel:/var/www/html/try-laraval
            - ../shayna-backend-laravue:/var/www/html/shayna-backend-laravue
        ports:
            - "9000:9000"
        networks:
            - laravel
