version: "3"

networks:
    laravel:

services:
    nginx:
        platform: linux/x86_64
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ..:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - php
        networks:
            - laravel

    php:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: azzam
                uid: 1000
        container_name: php
        volumes:
            - ..:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "9000:9000"
        networks:
            - laravel
